# Generated by Django 5.1.4 on 2024-12-09 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_cliente", models.CharField(max_length=100)),
                ("whatsapp", models.CharField(max_length=15)),
                ("bairro", models.CharField(max_length=100)),
                ("coordenadas", models.CharField(max_length=50)),
                (
                    "forma_pagamento",
                    models.CharField(
                        choices=[
                            ("pix", "Pix"),
                            ("dinheiro", "Dinheiro"),
                            ("debito", "Cartão Débito"),
                            ("credito", "Cartão Crédito"),
                        ],
                        max_length=20,
                    ),
                ),
                ("data_pedido", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Sabor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=30)),
                ("descricao", models.TextField()),
                ("preco", models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
