# Generated by Django 5.1.4 on 2024-12-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sabor",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to="imagens/"),
        ),
        migrations.AlterField(
            model_name="sabor",
            name="descricao",
            field=models.TextField(blank=True, help_text="Descrição dos igredientes"),
        ),
        migrations.AlterField(
            model_name="sabor",
            name="nome",
            field=models.CharField(
                help_text="Nome do sabor da esfiha", max_length=30, unique=True
            ),
        ),
    ]
