# Generated by Django 5.1.4 on 2024-12-29 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pedido",
            old_name="cliente",
            new_name="user",
        ),
    ]
