# Generated by Django 5.1.4 on 2024-12-14 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0002_sabor_imagem_alter_sabor_descricao_alter_sabor_nome"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, null=True)),
                ("whatsapp", models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name="pedido",
            old_name="data_pedido",
            new_name="criado_em",
        ),
        migrations.RemoveField(
            model_name="pedido",
            name="coordenadas",
        ),
        migrations.RemoveField(
            model_name="pedido",
            name="nome_cliente",
        ),
        migrations.RemoveField(
            model_name="pedido",
            name="whatsapp",
        ),
        migrations.AddField(
            model_name="pedido",
            name="endereco",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pedido",
            name="valor_total",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="bairro",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="forma_pagamento",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="pedido",
            name="cliente",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="delivery.cliente",
            ),
            preserve_default=False,
        ),
        migrations.RenameModel(
            old_name="Sabor",
            new_name="Produto",
        ),
        migrations.CreateModel(
            name="ItemPedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.PositiveIntegerField()),
                ("preco_unitario", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="delivery.pedido",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="delivery.produto",
                    ),
                ),
            ],
        ),
    ]
