# Generated by Django 5.1.4 on 2024-12-14 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0003_cliente_rename_data_pedido_pedido_criado_em_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="cliente",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="delivery.cliente",
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
