# Generated by Django 5.1.4 on 2024-12-30 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0003_rename_valor_total_pedido_total_pedido_subtotal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pedido",
            name="localizacao",
        ),
        migrations.AddField(
            model_name="pedido",
            name="taxa_entrega",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pedido",
            name="troco_para",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pedidos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
