# Generated by Django 5.1.4 on 2024-12-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0004_remove_pedido_localizacao_pedido_taxa_entrega_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pedido",
            old_name="troco_para",
            new_name="taxa_cartao_credito",
        ),
        migrations.RemoveField(
            model_name="itempedido",
            name="preco_unitario",
        ),
        migrations.AddField(
            model_name="pedido",
            name="troco",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
