# Generated by Django 5.1.4 on 2024-12-27 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0005_alter_produto_imagem"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bairro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50, unique=True)),
                ("taxa_entrega", models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.AddField(
            model_name="cliente",
            name="endereco",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="pedido",
            name="localizacao",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="produto",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to="imagens/"),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="bairro",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="delivery.bairro",
            ),
        ),
    ]
