# Generated by Django 5.1.4 on 2025-01-02 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_pedido_itens_txt_alter_pedido_endereco_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='itens_txt',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='endereco',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='forma_pagamento',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='taxa_entrega',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='Itens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido', to='delivery.pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='delivery.produto')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='itens',
            field=models.ManyToManyField(through='delivery.Itens', to='delivery.produto'),
        ),
        migrations.DeleteModel(
            name='ItemPedido',
        ),
    ]
