# Generated by Django 5.1.4 on 2025-01-02 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_remove_pedido_itens_txt_alter_pedido_endereco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='bairro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bairro', to='delivery.bairro'),
        ),
    ]
