# Generated by Django 5.1.4 on 2025-01-09 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0011_pedido_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Itens',
        ),
    ]
