# Generated by Django 5.1.4 on 2025-01-16 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0013_categoria_pedido_pago_produto_disponivel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pontos',
            field=models.IntegerField(default=0),
        ),
    ]
