# Generated by Django 5.1.4 on 2025-01-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0015_funcionamento_alter_produto_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionamento',
            name='dia',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='funcionamento',
            name='hora_abertura',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funcionamento',
            name='hora_fechamento',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
