# Generated by Django 5.1.4 on 2025-01-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0016_funcionamento_dia_funcionamento_hora_abertura_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoLoja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loja_aberta', models.BooleanField(default=True)),
                ('mensagem_fechada', models.TextField(default='Estamos fechados no momento.')),
                ('imagem_fechada', models.ImageField(blank=True, null=True, upload_to='imagens/loja/')),
            ],
        ),
        migrations.DeleteModel(
            name='Funcionamento',
        ),
    ]
