# Generated by Django 5.1.4 on 2025-01-20 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0017_configuracaoloja_delete_funcionamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='pontos_ganhos',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
