# Generated by Django 5.1.4 on 2025-01-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0019_produto_trocavel_por_pontos'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='pontos_troca',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
