# Generated by Django 5.1.4 on 2025-01-22 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0020_produto_pontos_troca'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ultimo_endereco',
            field=models.TextField(blank=True, null=True),
        ),
    ]
