# Generated by Django 5.1.5 on 2025-01-23 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0021_user_ultimo_endereco"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
